# Generated by Django 3.2.6 on 2021-08-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='price_Range',
        ),
    ]
